name: FloatingItems
main: me.seetch.floatingitems.FloatingItemsPlugin
version: "${pom.version}"
api: 1.0.13
authors:
  - "https://github.com/seetch"
website: "https://github.com/seetch/FloatingItemsPlugin"